FROM golang:1.20-bullseye

RUN apt-get update \
    && apt install apt-transport-https build-essential curl gnupg2 lintian rsync rubygems-integration ruby-dev ruby -qy \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN gem install --quiet rake fpm package_cloud

WORKDIR /src
